package squaringNumbers

import "github.com/tushar2708/conveyor"

// NumberSource generates a sequence of numbers (0...CountLimit)
type NumberSource struct {
	*conveyor.ConcreteSourceExecutor[int]
	CountLimit int
}

// SquareOperator squares the numbers generated by NumberSource
type SquareOperator struct {
	*conveyor.ConcreteOperationExecutor[int, int]
}

// PrinterSink prints the final numbers
type PrinterSink struct {
	*conveyor.ConcreteSinkExecutor[int]
}

// AdditionOperator adds a configurable number
type AdditionOperator struct {
	*conveyor.ConcreteOperationExecutor[int, int]
	ToAdd int
}

// PrinterSink1 has slightly different Execute() method
type PrinterSink1 struct {
	*conveyor.ConcreteSinkExecutor[int]
}

// PrinterSink2 has slightly different Execute() method
type PrinterSink2 struct {
	*conveyor.ConcreteSinkExecutor[int]
}

// PrinterSink3 has slightly different Execute() method
type PrinterSink3 struct {
	*conveyor.ConcreteSinkExecutor[int]
}
